FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Run CPU helper in background, then your script
CMD ["sh", "-c", "python cpu_stress_helper.py & python device_simulator.py"]